version: "3.7"

services:
  db:
    image: ramsrib/pgvector
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=langchain
    volumes:
       - ./postgres:/data/postgres
    networks:
      - dev

networks:
  dev:
    driver: bridge